---
- name: config | Configuring RabbitMQ
  ansible.builtin.template:
    src: "{{ rabbitmq_config_file }}"
    dest: "/etc/rabbitmq/rabbitmq.config"
    mode: u=rw,g=r,o=r
  become: true
  notify: "restart rabbitmq-server"

- name: config | Configuring RabbitMQ environemnt
  ansible.builtin.template:
    src: "{{ rabbitmq_config_env_file }}"
    dest: "/etc/rabbitmq/rabbitmq-env.conf"
    mode: u=rw,g=r,o=r
  become: true
  notify: "restart rabbitmq-server"
