---
- name: fedora | installing pre-reqs
  ansible.builtin.dnf:
    name: ['wget']
    state: present
  become: true
  register: result
  until: result is successful

- name: fedora | installing erlang
  ansible.builtin.dnf:
    name: ['erlang']
    state: present
  become: true
  register: result
  until: result is successful

- name: fedora | adding RabbitMQ public GPG key
  ansible.builtin.rpm_key:
    key: "{{ rabbitmq_redhat_repo_key }}"
    state: present
  become: true
  register: result
  until: result is successful

- name: fedora | downloading RabbitMQ
  ansible.builtin.get_url:
    url: "{{ rabbitmq_redhat_url }}/{{ rabbitmq_redhat_package }}"
    dest: "/opt/{{ rabbitmq_redhat_package }}"
    mode: u=rw,g=r,o=r
  become: true

- name: fedora | installing RabbitMQ
  ansible.builtin.dnf:
    name: "/opt/{{ rabbitmq_redhat_package }}"
    state: present
  become: true
  register: result
  until: result is successful

- name: fedora | starting and enabling RabbitMQ service
  ansible.builtin.service:
    name: rabbitmq-server
    state: started
    enabled: true
  become: true
