---
- name: rabbitmq_plugins | installing plugin(s)
  community.rabbitmq.rabbitmq_plugin:
    name: "{{ rabbitmq_plugins }}"
  become: true
  when: rabbitmq_plugins | length > 0
  notify: restart rabbitmq-server
